### ISSUE TITLE
App Template

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia-app#1]
Hi @carcablop and @miquelduranfrigola ,

I have created this template for the streamlit app as a temporary GUI while we work on the full one. I have used the open source malaria as an example, and the model checkpoints are in the directory. We now need to work on this so that the streamlit app takes the model from the deployed DO service, and also automatically reads the metadata to update relevant fields.
I am open to suggestions to making this easier. Meanwhile, I will deploy the OSM models as models in the Ersilia Model Hub and upload them to DO so we can start trying it out.

**Comment by carcablop** [comment]
Hi @GemmaTuron 

Thank you so much. I was testing streamlit with an example (molecular weight), to explore the application. I made a small example that the molecular weight is calculated given an input.
But I was stuck on how to do it for all the models, and it was to make the queries to the airtable to bring the models that were already deployed and thus also bring me the metadata.

From what I understand from what you propose, therefore we would make the POST request to the URL of the API of the model that is already deployed (Example: https://eos80ch-m365k.ondigitalocean.app/run) and then we would process the response depending on each model. Therefore we would not need to add the checkpoints of each model to the directory.
For the model metadata, too, we would make a POST request to the example URL: https://eos80ch-m365k.ondigitalocean.app/info and process the output data to display it in the app.

I'll work on this for the two example models that are already deployed in DO. Additionally, I would like to add a button that runs the model and obtains the results.

**Comment by GemmaTuron** [comment]
@carcablop 

We are working today with @miquelduranfrigola to make an easier api to call the models from DO - will keep you posted.
Meanwhile, I do think that a button to RUN instead of just hitting enter would be helpful for me as well, if you want to figure out that feature that would be fantastic!

**Comment by carcablop** [comment]
Hello @GemmaTuron.
I have run the application in my local, with the example of OSM, I suggested making some changes in the design of the application such as:

1. Do not show the dataframe as a result, it looked better before, when the image of the molecule was printed and the results were in a column next to it, from my point of view it is more visual. Or if you prefer to print the table, we could change the font size and improve the style of the table, including even an image, and not print the key column.
2. The description of the model is better on one side. That the main session to run the model is only the text area and the results.
3. We can add an icon, it can be an ersilia icon or icons that help to illustrate the information sessions.
5. Improve the text that will follow Input Molecules, such as: 'Enter a list of molecules using smile notation and each molecule on a separate line

**Comment by carcablop** [comment]
@GemmaTuron , I have made the above changes, but I did it from a branch that I create, but I don't have permissions on this repository to make changes.

So here from the fork of my repository you can see the changes. [https://github.com/carcablop/ersilia-app/commit/62c172e0d368c0935b82a6693f909da500f6eb2d](https://github.com/carcablop/ersilia-app/commit/62c172e0d368c0935b82a6693f909da500f6eb2d)

**Comment by carcablop** [comment]
@GemmaTuron I also add the option to upload a csv file:  [https://github.com/carcablop/ersilia-app/commit/89c69545a63cc64a91cf7ced479eee372dc091f3](https://github.com/carcablop/ersilia-app/commit/89c69545a63cc64a91cf7ced479eee372dc091f3)

**Comment by GemmaTuron** [comment]
Hi @carcablop 

Excellent suggestions, thanks for acting so fast. Could you open a PR? Im currently wrangling with the deployment to Digital Ocean to make it work online, I'll follow up with you when I succeed!

**Comment by GemmaTuron** [comment]
Hi @carcablop and @miquelduranfrigola 

I've merged Carolina's suggestions and worked from there. The main changes are:
- Colour is set to Ersilia's color code, in the `.streamlit/config.toml` file (it was not picking it up otherwise)
- I've added Ersilia's logo
- I've changed the input to forms just because they have more functionalities compared to the buttons we were using, thanks for implementing the .csv uploader Carolina!
- I've removed two of the new features: the emojis, because each model should have different emojis depending on what they do, so better not to get into this, and the output, because while I like a lot to see the drawings, users might submit hundreds of molecules and this would significantly slow the app.

It now looks simple but straightforward, I hope you like it!
The app is also [live online](https://ersilia-app-t5zpw.ondigitalocean.app/?model_id=eos7yti)

**Comment by carcablop** [comment]
Hi @GemmaTuron 
It looks great, now It look very Ersilia!. 
I suggest something else, a visual indicator that the model is running, and the user doesn't have the feeling that nothing is happening.
I have had many problems with my internet connection, and when I tried to run it I thought there was a problem with the application and the problem is that it was taking a long time to run.

With `**st.spinner** ` [https://docs.streamlit.io/library/api-reference/status/st.spinner](https://docs.streamlit.io/library/api-reference/status/st.spinner) . I can do it.

**Comment by GemmaTuron** [comment]
yes, I like that! 
Thanks for the suggestion!!

**Comment by GemmaTuron** [comment]
I've changed the input of .csv files since in the text we ask for SMILES as a column but then we look for 'smiles'
Also added an error so that user knows

**Comment by GemmaTuron** [comment]
The app is working, we have a few models in it already:
https://ersilia-app-t5zpw.ondigitalocean.app/?model_id=eos4rta
